# week08/k8s/order-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w08e1 # Deployment name matches
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: sit722week07.azurecr.io/order_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        # Database connection details
        - name: POSTGRES_HOST
          value: order-db-service-w08e1
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1 # ConfigMap name matches
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1 # Secret name matches
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-w08e1 # Secret name matches
              key: POSTGRES_PASSWORD
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-w08e1 # ConfigMap name matches
              key: PRODUCT_SERVICE_URL # This will be the internal ClusterIP for the Product Service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-w08e1 # Service name matches
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
