name: E-commerce CI/CD

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies (Product + Order services)
        run: |
          pip install pytest
          pip install -r backend/product_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
      - name: Run backend tests
        run: |
          if [ -d backend/product_service/tests ]; then
            pytest backend/product_service/tests || echo "No product service tests found."
          fi
          if [ -d backend/order_service/tests ]; then
            pytest backend/order_service/tests || echo "No order service tests found."
          fi

  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Locate frontend
        run: |
          if [ -d frontend ]; then
            echo "FRONTEND_PATH=frontend" >> $GITHUB_ENV
          elif [ -d example_3/frontend ]; then
            echo "FRONTEND_PATH=example_3/frontend" >> $GITHUB_ENV
          elif [ -d week08/frontend ]; then
            echo "FRONTEND_PATH=week08/frontend" >> $GITHUB_ENV
          else
            echo "Frontend folder not found!" && exit 1
          fi
      - name: Install & Build
        run: |
          npm install --prefix $FRONTEND_PATH
          npm run build --prefix $FRONTEND_PATH
      - name: Run frontend tests (if exist)
        run: |
          if [ -f $FRONTEND_PATH/package.json ] && grep -q "\"test\":" $FRONTEND_PATH/package.json; then
            npm test --prefix $FRONTEND_PATH || echo "No frontend tests defined."
          else
            echo "No frontend test script found."
          fi

  cd:
    needs: [backend-ci, frontend-ci]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group sit722-noor-rg --name sit722nooraks --overwrite-existing
          kubectl apply -f k8s/
