name: E-commerce CI/CD with Docker

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run with docker-compose
        run: |
          docker-compose -f docker-compose.test.yml up --build -d
          # wait for services to be healthy
          sleep 20
          docker-compose -f docker-compose.test.yml run backend pytest
          docker-compose -f docker-compose.test.yml down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to AKS
        run: |
          az aks get-credentials --resource-group sit722-noor-rg --name sit722nooraks --overwrite-existing
          kubectl apply -f k8s/
